language: python
python:
- '2.7'

sudo: required
services:
- docker
before_install:
- docker pull f5devcentral/containthedocs
install: true
script:
 - ./scripts/docker-docs.sh ./scripts/test-docs.sh
deploy:
- provider: script
  skip_cleanup: true
  script:
  - ./scripts/deploy-docs.sh publish-container-docs-to-prod containers v1
